server:
  port: 8080
  servlet:
    jsp:
      init-parameters:
        development: true
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: sbsst
    url: jdbc:mysql://localhost:3306/portfolio?characterEncoding=UTF-8&serverTimezone=UTC
    username: sbs123414
